#!/usr/bin/env bash
#
# Publishes the Homebrew cask for a release into the personal tap.
#
# Writes exactly one file, Casks/hafifpix.rb, through the GitHub contents API.
# Nothing else in that tap is read, cloned or rewritten, so nothing here can
# reach the other casks living beside it.
#
# The hash must be of the DMG as published, not as built: notarytool staples
# the ticket into the image after make dmg produces it, which changes the
# bytes. Pass the file that was uploaded, or none at all and it fetches the
# one on the release.
#
#   scripts/update-tap.sh 1.3.1                      # hash the published DMG
#   scripts/update-tap.sh 1.3.1 dist/release/x.dmg   # hash a local file
#   DRY_RUN=1 scripts/update-tap.sh 1.3.1            # print, publish nothing

set -euo pipefail

TAP="${HAFIFPIX_TAP:-doguyilmaz/homebrew-tap}"
REPO="${HAFIFPIX_REPO:-doguyilmaz/hafifpix}"
CASK_PATH="Casks/hafifpix.rb"
VERSION="${1:?usage: update-tap.sh <version> [dmg]}"
DMG="${2:-}"

# The workflow token is scoped to this repository and cannot write to the tap,
# so a release publishes the cask only when a token for it exists. Missing is
# not a failure: the release itself is already out, and a stale cask is a
# smaller problem than a red pipeline that stops future ones.
if [ -n "${HOMEBREW_TAP_GITHUB_TOKEN:-}" ]; then
    export GH_TOKEN="$HOMEBREW_TAP_GITHUB_TOKEN"
elif [ -n "${CI:-}" ]; then
    echo "note: HOMEBREW_TAP_GITHUB_TOKEN unset — skipping the cask update for $VERSION." >&2
    echo "      The release is unaffected. Add the secret to publish to $TAP." >&2
    exit 0
fi

if [ -z "$DMG" ]; then
    WORK=$(mktemp -d)
    trap 'rm -rf "$WORK"' EXIT
    gh release download "v$VERSION" --repo "$REPO" \
        --pattern "HafifPix-$VERSION.dmg" --dir "$WORK"
    DMG="$WORK/HafifPix-$VERSION.dmg"
fi
[ -f "$DMG" ] || { echo "error: $DMG not found" >&2; exit 1; }

SHA=$(shasum -a 256 "$DMG" | cut -d' ' -f1)

# `auto_updates true` is the stanza that keeps Homebrew and Sparkle out of each
# other's way: the app updates itself, so `brew upgrade` leaves it alone rather
# than reinstalling over a copy that is already newer than the cask says.
#
# `binary` is what makes this worth more than a nicer download. The `hafif`
# tool ships inside the bundle and until now reached PATH only by running
# `make install-cli` by hand; Homebrew symlinks it on install and removes it
# on uninstall. It follows `app`, which is what puts the bundle in place for
# it to point at.
CASK=$(
    cat <<RUBY
# Generated by scripts/update-tap.sh in doguyilmaz/hafifpix. DO NOT EDIT.
cask "hafifpix" do
  version "$VERSION"
  sha256 "$SHA"

  url "https://github.com/$REPO/releases/download/v#{version}/HafifPix-#{version}.dmg"
  name "HafifPix"
  desc "Native macOS image optimizer"
  homepage "https://github.com/$REPO"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates true
  depends_on macos: :sequoia

  app "HafifPix.app"
  binary "#{appdir}/HafifPix.app/Contents/Resources/bin/hafif"

  uninstall quit: "com.doguyilmaz.HafifPix"

  zap trash: [
    "~/Library/Caches/com.doguyilmaz.HafifPix",
    "~/Library/HTTPStorages/com.doguyilmaz.HafifPix",
    "~/Library/Preferences/com.doguyilmaz.HafifPix.plist",
  ]
end
RUBY
)

if [ -n "${DRY_RUN:-}" ]; then
    printf '%s\n' "$CASK"
    exit 0
fi

# Branch on the exit code, not on whether anything came back: `gh api` prints
# its error body to stdout, so a missing file answers with a JSON 404 that is
# every bit as non-empty as a real cask.
if current=$(gh api "repos/$TAP/contents/$CASK_PATH" \
    -H "Accept: application/vnd.github.raw" 2>/dev/null); then
    exists=1
else
    exists=0
    current=""
fi

if [ "$current" = "$CASK" ]; then
    echo "cask already at $VERSION, nothing to publish"
    exit 0
fi

CONTENT=$(printf '%s\n' "$CASK" | base64 | tr -d '\n')

if [ "$exists" = 1 ]; then
    gh api "repos/$TAP/contents/$CASK_PATH" -X PUT \
        -f "message=Brew cask update for hafifpix version v$VERSION" \
        -f "content=$CONTENT" \
        -f "sha=$(gh api "repos/$TAP/contents/$CASK_PATH" --jq .sha)" \
        --jq '.commit.html_url'
else
    gh api "repos/$TAP/contents/$CASK_PATH" -X PUT \
        -f "message=Brew cask update for hafifpix version v$VERSION" \
        -f "content=$CONTENT" \
        --jq '.commit.html_url'
fi
